[workaround]docker build: no cache (#1829)
Since using "cache" will cause:

> ERROR: failed to solve: cannot copy from stage "cache", it needs to be defined before current stage "builder"